# =============================================================================
# Wiki Chatbot - Secrets設定ファイル
# =============================================================================
# このファイルをsecrets.tomlにコピーして、実際の値を入力してください

# =============================================================================
# LLMプロバイダー API Keys（最低1つは必須）
# =============================================================================

# OpenAI API Key（推奨）
# 取得先: https://platform.openai.com/api-keys
OPENAI_API_KEY = "sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Anthropic API Key
# 取得先: https://console.anthropic.com/
ANTHROPIC_API_KEY = "sk-ant-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Google Gemini API Key
# 取得先: https://ai.google.dev/
GOOGLE_API_KEY = "AIzaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# =============================================================================
# GitHub永続化設定（必須）
# =============================================================================

# GitHubリポジトリURL
GITHUB_REPO_URL = "https://github.com/yourusername/wiki-chatbot-data.git"

# GitHub Personal Access Token
# 取得方法:
# 1. GitHub → Settings → Developer settings → Personal access tokens → Tokens (classic)
# 2. Generate new token → repo権限を選択
GITHUB_TOKEN = "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# =============================================================================
# 自動バックアップ設定
# =============================================================================

# メッセージ間隔でのバックアップ（デフォルト: 10回）
BACKUP_INTERVAL_MESSAGES = 10

# =============================================================================
# 認証設定
# =============================================================================

# 認証パスワード
AUTH_PASSWORD = "your_secure_password"

# 許可されたメールドメイン（@以降）
ALLOWED_EMAIL_DOMAIN = "farmnote.jp"

# =============================================================================
# システム設定
# =============================================================================

# デバッグモード（true/false）
DEBUG_MODE = true

# アプリタイトル
APP_TITLE = "社内Wiki検索チャットボット"

# =============================================================================
# 高度な設定（通常は変更不要）
# =============================================================================

# チャット履歴保持期間（日）
CHAT_HISTORY_RETENTION_DAYS = 30

# 1日あたりのクエリ制限
DAILY_QUERY_LIMIT = 100

# RAG検索結果数
RAG_TOP_K = 5

# テキストチャンクサイズ
TEXT_CHUNK_SIZE = 1000

# テキストチャンクオーバーラップ
TEXT_CHUNK_OVERLAP = 200