# 最小限設定版 - 動作に必要な最低限の設定

# LLM API Key（OpenAIを推奨）
OPENAI_API_KEY = "sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# GitHub永続化設定
GITHUB_REPO_URL = "https://github.com/yourusername/wiki-chatbot-data.git"
GITHUB_TOKEN = "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# 認証設定
AUTH_PASSWORD = "your_password"
ALLOWED_EMAIL_DOMAIN = "yourcompany.com"